{application,wallaby,
             [{registered,[]},
              {description,"Concurrent feature tests for elixir"},
              {vsn,"0.5.0"},
              {modules,['Elixir.Wallaby','Elixir.Wallaby.AmbiguousMatch',
                        'Elixir.Wallaby.BadMetadata','Elixir.Wallaby.DSL',
                        'Elixir.Wallaby.Driver',
                        'Elixir.Wallaby.ElementNotFound',
                        'Elixir.Wallaby.ExpectationNotMet',
                        'Elixir.Wallaby.Helpers.KeyCodes',
                        'Elixir.Wallaby.Metadata','Elixir.Wallaby.NoBaseUrl',
                        'Elixir.Wallaby.Node','Elixir.Wallaby.Phantom',
                        'Elixir.Wallaby.Server','Elixir.Wallaby.Session',
                        'Elixir.Wallaby.XPath','Elixir.Wallaby.XPath.Builder',
                        'Elixir.Wallaby.XPath.Render']},
              {applications,[kernel,stdlib,elixir,logger,httpoison]},
              {mod,{'Elixir.Wallaby',[]}}]}.